AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to deploy IAM Role, Glue Job, Step Function, SQS Queue, and SNS Topic"

Resources:

  GlueStepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GlueStepFunctionExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
                - states.amazonaws.com
                - sqs.amazonaws.com
                - sns.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GlueStepFunctionSQSSNSPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                  - glue:GetJobRun
                  - glue:GetJobRuns
                Resource: "*"
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueUrl
                Resource: "*"
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: "*"
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: "*"


  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: DataProcessingGlueJob
      Role: !GetAtt GlueStepFunctionRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: s3://your-bucket10/path/to/script.py
        PythonVersion: "3"
      DefaultArguments:
        "--job-language": "python"
        "--TempDir": "s3://your-bucket10/temp/"
      MaxRetries: 1
      GlueVersion: "3.0"
      NumberOfWorkers: 2
      WorkerType: G.1X


  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MyMessageQueue


  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: DataProcessingNotifications
      TopicName: DataProcessingTopic


  StepFunction:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: DataProcessingWorkflow
      RoleArn: !GetAtt GlueStepFunctionRole.Arn
      DefinitionString:
        Fn::Sub: |
          {
            "Comment": "Step Function to orchestrate Glue Job, SQS, and SNS",
            "StartAt": "Start",
            "States": {
              "Start": {
                "Type": "Pass",
                "Next": "Trigger Glue Job"
              },
              "Trigger Glue Job": {
                "Type": "Task",
                "Resource": "arn:aws:states:::glue:startJobRun.sync",
                "Parameters": {
                  "JobName": "DataProcessingGlueJob"
                },
                "Next": "Send Message to SQS"
              },
              "Send Message to SQS": {
                "Type": "Task",
                "Resource": "arn:aws:states:::sqs:sendMessage",
                "Parameters": {
                  "QueueUrl": "${SQSQueue}",
                  "MessageBody": "Glue Job Completed Successfully"
                },
                "Next": "Send SNS Notification"
              },
              "Send SNS Notification": {
                "Type": "Task",
                "Resource": "arn:aws:states:::sns:publish",
                "Parameters": {
                  "TopicArn": "${SNSTopic}",
                  "Message": "Step Function Workflow Completed Successfully"
                },
                "End": true
              }
            }
          }

Outputs:
  StepFunctionArn:
    Description: "ARN of the Step Function"
    Value: !Ref StepFunction

  SQSQueueUrl:
    Description: "URL of the SQS Queue"
    Value: !Ref SQSQueue

  SNSTopicArn:
    Description: "ARN of the SNS Topic"
    Value: !Ref SNSTopic